(function(app) {
  app.routing = ng.router.RouterModule.forRoot([
  	{path: '', redirectTo: 'loading', pathMatch: 'full'},
  	{path: 'menu',component:app.MenuComponent},
	{path: 'loading',component:app.LoadingAppComponent},
	{path: 'terminal-report',component:app.TerminalReportComponent},
	{path: 'terminal-create',component:app.TerminalCreateComponent},
	{path: 'terminal-update',component:app.TerminalCreateComponent},
	{path: 'terminal-view',component:app.TerminalViewComponent},
	{path: 'propietario-create',component:app.PropietarioCreateComponent},
	{path: 'propietario-update',component:app.PropietarioCreateComponent},
	{path: 'propietario-view',component:app.PropietarioViewComponent},
	{path: 'propietario-report',component:app.PropietarioReportComponent},
	{path: 'check-passenger', component:app.CheckPassengerComponent},
	{path: 'reservation-report-line',component:app.ReservationReportComponent},
	{path: 'reservation-report',component:app.ReservationAllReportComponent},
	{path: 'reservation-view-line',component:app.ReservationViewComponent},
	{path: 'parada-create',component:app.ParadaCreateComponent},
	{path: 'parada-report',component:app.ParadaReportComponent},
	{path: 'car-type-create',component:app.CarTypeCreateComponent},
	{path: 'car-type-update',component:app.CarTypeCreateComponent},
	{path: 'car-type-view',component:app.CarTypeViewComponent},
	{path: 'car-type-report',component:app.CarTypeReportComponent},
	{path: 'passenger-report',component:app.PassengerReportComponent},
	{path: 'passenger-create',component:app.PassengerCreateComponent},
	{path: 'passenger-update',component:app.PassengerCreateComponent},
	{path: 'passenger-view',component:app.PassengerViewComponent},
	{path: 'fare-create',component:app.FareCreateComponent},
	{path: 'fare-update',component:app.FareCreateComponent},
	{path: 'fare-report',component:app.FareReportComponent},
	{path: 'driver-report',component:app.DriverReportComponent},
	{path: 'driver-create',component:app.DriverCreateComponent},
	{path: 'driver-update',component:app.DriverCreateComponent},
	{path: 'check-trip',component:app.CheckTripComponent},
	{path: 'currency-exchange-report', component:app.CurrencyExchangeReportComponent},
	{path: 'currency-exchange-create', component:app.CurrencyExchangeCreateComponent},
	{path: 'line-report', component:app.LineReportComponent},
	{path: 'line-view', component:app.LineViewComponent},
	{path: 'line-create', component:app.LineCreateComponent},
	{path: 'line-update', component:app.LineCreateComponent},
	{path: 'line-view-propietario', component:app.LineViewPropietarioComponent},
	{path: 'line-view-car', component:app.LineViewCarComponent},
	
	{path: 'car-report', component:app.CarReportComponent},
	{path: 'car-create', component:app.CarCreateComponent},
	{path: 'car-update', component:app.CarCreateComponent},
	{path: 'car-view', component:app.CarViewComponent},
	
	{path: 'route-report', component:app.RouteReportComponent},
	{path: 'route-create', component:app.RouteCreateComponent},
	{path: 'route-update', component:app.RouteCreateComponent},
	{path: 'route-view', component:app.RouteViewComponent},
	
	{path: 'schedule-report', component:app.ScheduleReportComponent},
	{path: 'schedule-create', component:app.ScheduleCreateComponent},
	{path: 'schedule-update', component:app.ScheduleCreateComponent},
	
	{path: 'travel-report', component:app.TravelReportComponent},
	{path: 'travel-report-line', component:app.TravelReportLineComponent},
	{path: 'travel-create', component:app.TravelCreateComponent},
	{path: 'travel-create-line', component:app.TravelCreateLineComponent},
	{path: 'travel-update', component:app.TravelCreateComponent},
	{path: 'travel-view', component:app.TravelViewComponent},
	{path: 'travel-passengers', component:app.TripPassengerComponent},
	{path: 'add-payment', component:app.PaymentAddComponent},
	{path: 'add-payment-taquilla', component:app.PaymentAddComponent},
	{path: 'sales-report',component:app.SalesReportComponent},
	{path: 'new-sales-line',component:app.NewSalesComponent},
	{path: 'general-report-sales',component:app.GeneralReportSalesComponent},
	{path: 'sales-report-line',component:app.SalesLineReportComponent},
	
	{path: 'guide-oper',component:app.GuideOperComponent},
	{path: 'guide-super',component:app.GuideSuperComponent},
	{path: 'guide-rec',component:app.GuideRecComponent},
	
	{path: 'settings', component:app.SettingsComponent},
	{path: 'not-user', component:app.NotUserComponent},
	{path: "fast-entry-line", component:app.FastEntryLine},
	{path: "fast-entry", component:app.FastEntryLine},
	{path: "price-short-route-report", component:app.PriceShortRouteReportComponent},
	{path: "price-short-route-create", component:app.PriceShortRouteCreateComponent},
	{path: 'ticket-preimpreso',component:app.TicketPreimpresoComponent},
	{path:'**' , component:app.MenuComponent}
  ],{useHash: true});
})(window.app || (window.app = {}));